// PLEASE FOLLOW THIS FORMAT TO AVOID BREAKING THE PAGE
/*
[Category]: [
  [Command Name, Command Description]
]
*/

export const commandsRef = {
  Public: [
    ["avatar", "Gets the avatar of a user."],
    ["reminder create", "Create a reminder."],
    ["reminder list", "View your reminders."],
    ["reminder delete", "Delete a reminder."],
    ["reminder", "Reminder system."],
    ["suggest", "Make a suggestion."],
    ["verify", "Start/complete verification used for the guild."],
  ],
  Fun: [
    ["8ball", "Ask the magic 8ball a question."],
    ["cat", "Get a random cat image!"],
    ["coinflip", "Flip a coin."],
    ["dadjoke", "Receive a random dad joke!"],
    ["dice", "Roll a die."],
    ["meme", "Send a fantastic meme."],
    ["quote", "Receive a random joke from a category."],
    ["slap", "Slap someone"],
  ],
  Information: [
    ["botinfo", "Receive information about the bot."],
    ["channelinfo", "Receive information about the current channel."],
    ["help", "Get help from the bot."],
    ["invite", "Sends an invite of the bot to the user"],
    ["ping", "Ping pong!"],
    ["serverinfo", "Receive information about the current guild."],
    ["support", "Sends an invite to the support server."],
    ["uptime", "View the bot's uptime."],
    ["userinfo", "Shows information about a user."]
  ],
  Moderation: [
    ["announce", "Announce a message to the server."],
    ["audit", "Displays the audit log for the server."],
    ["ban", "Bans a member of the server."],
    ["bans view", "View the logged bans of a user"],
    ["bans removelog", "Removes a logged ban from a member of the server"],
    ["bans", "Ban logging system."],
    ["clear", "Bulk delete messages."],
    ["kick", "Kicks a member of the server."],
    ["kicks view", "View the logged kicks of a user"],
    ["kicks removelog", "Removes a logged kick from a member of the server"],
    ["kicks", "Kick logging system."],
    ["lockdown", "Prevents members from sending messages in the channel."],
    ["slowmode", "Sets the slowmode of the channel."],
    ["softban", "Bans and unbans member of the server to delete their messages."],
    ["tempban", "Temporarily bans a member of the server."],
    ["ticket close", "Close the ticket."],
    ["ticket block", "Block a user from creating tickets."],
    ["ticket unblock", "Unblock a user from creating tickets."],
    ["ticket view_previous", "View a user's previous tickets."],
    ["ticket add_user", "Give a user permission to view a ticket."],
    ["ticket remove_user", "Remove permission from a user to view a ticket."],
    ["ticket", "Ticket system."],
    ["timeout", "Timeout a member of the server."],
    ["timeouts view", "View the logged timeouts of a user"],
    ["timeouts removelog", "Removes a logged timeout from a member of the server"],
    ["timeouts", "Timeout logging system."],
    ["unban", "Unbans a member of the server."],
    ["unlock", "Allows members to send messages in the channel"],
    ["warn", "Warns a member of the server."],
    ["warns view", "View the logged warns of a user"],
    ["warns removelog", "Removes a logged warn from a member of the server"],
    ["warns", "Warn logging system."],
  ],
  Admin: [
    ["antiraid setup", "Configure the anti-raid protection system."],
    ["antiraid disable", "Disable the anti-raid protection system."],
    ["antiraid start_raid", "Manually start the anti-raid protection system."],
    ["antiraid stop_raid", "Stop the anti-raid protection system if triggered."],
    ["antiraid", "Anti-raid protection system."],
    ["autorole setup", "Configure the auto-role system."],
    ["autorole disable", "Disable the auto-role system."],
    ["autorole", "Autorole system."],
    ["giveaway create", "Create a giveaway."],
    ["giveaway cancel", "Cancel a giveaway."],
    ["giveaway end", "Manually end a giveaway."],
    ["giveaway reroll", "Reroll a giveaway."],
    ["giveaway", "Giveaway system."],
    ["logging setup", "Configure the logging system."],
    ["logging disable", "Disable the logging system."],
    ["logging", "Logging system."],
    ["poll", "Start a poll."],
    ["reactionrole", "Create a reaction role message."],
    ["setup", "Setup basic bot stuff."],
    ["suggestion setup", "Setup the suggestion system."],
    ["suggestion disable", "Disable the suggestion system."],
    ["suggestion", "Suggestion system."],
    ["ticket_admin setup", "Configure the ticket system."],
    ["ticket_admin disable", "Disable the ticket system."],
    ["ticket_admin", "Ticket system management."],
    ["verification setup", "Configure the verification system."],
    ["verificiation disable", "Disable the verification system."],
    ["verification", "Verification system."]
  ],
  Crisis: [
    ["crisis", "Gives you global crisis hotlines"]
  ]
}
